<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <OutputType>Exe</OutputType>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <SelfContained>true</SelfContained>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AssemblyName />
        <Company />
        <Product />
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.8" />
        <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.8" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.8" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.8" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.8" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />

        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.3.8" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.10" />
        <PackageReference Include="SukiUI" Version="6.0.4-nightly20251023" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\TableConverter.DataGeneration\TableConverter.DataGeneration.csproj" />
        <ProjectReference Include="..\TableConverter.FileConverters\TableConverter.FileConverters.csproj" />
    </ItemGroup>

    <ItemGroup>
        <UpToDateCheckInput Remove="Views\DataGenerationPageView.axaml" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Extenstions\" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Views\Workspaces\BaseWorkspaceEditorView.axaml.cs">
        <DependentUpon>BaseWorkspaceEditorView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\Documents\TableDataView.axaml.cs">
        <DependentUpon>TableDataView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>
</Project>
