<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <SelfContained>true</SelfContained>
        <AssemblyName />
        <Company />
        <Product />
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.12" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.12" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.12" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
        
        <PackageReference Include="Markdown.Avalonia" Version="11.0.2" />
        <PackageReference Include="SukiUI" Version="6.0.4-nightly20260107" />
        <PackageReference Include="TreeDataGrid.Avalonia" Version="11.3.0" />
        <PackageReference Include="Xaml.Behaviors.Avalonia" Version="11.3.9.5" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\TableConverter.DataGeneration\TableConverter.DataGeneration.csproj" />
        <ProjectReference Include="..\TableConverter.FileConverters\TableConverter.FileConverters.csproj" />
    </ItemGroup>

    <ItemGroup>
        <UpToDateCheckInput Remove="Views\DataGenerationPageView.axaml" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Views\Workspaces\BaseWorkspaceEditorView.axaml.cs">
        <DependentUpon>BaseWorkspaceEditorView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\Documents\TableDataView.axaml.cs">
        <DependentUpon>TableDataView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <None Update="appsettings.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>
</Project>
