<Project Sdk="Microsoft.NET.Sdk.WebAssembly">

    <PropertyGroup>
        <TargetFramework>net9.0-browser</TargetFramework>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <WasmBuildNative>true</WasmBuildNative>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Avalonia.Browser" Version="11.3.12" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TableConverter\TableConverter.csproj" />
    </ItemGroup>

</Project>
