using System;

namespace TableConverter.Views.Controls.Spreadsheet;

public static class ReferenceHelper
{
    //columnID starts counting from 0, workbook starts counting from 1, we use input 0->A
    public static string ToColumnLetter(int columnId)
    {
        int readableId = columnId + 1;
        
        // No need to use stringbuilder, it is generated by reverse engineering, and the cost is not high.
        var columnName = string.Empty;

        while (readableId > 0)
        {
            var modulo = (readableId - 1) % 26;
            columnName = Convert.ToChar('A' + modulo) + columnName;
            readableId = (readableId - modulo) / 26;
        }

        return columnName;
    }
}